import os

ROUTER_1INCH_TOKEN = os.getenv("ROUTER_TOKEN", "Aa9VksVszqXDod6Smp2TQGsJ6OkHHnzJ")
WEB3_PROVIDER_URL = os.getenv("WEB3_PROVIDER_URL", "http://127.0.0.1:8545")
EXPLORER_URL = os.getenv("EXPLORER_URL", "https://api.etherscan.io/api")
EXPLORER_TOKEN = os.getenv("EXPLORER_TOKEN", "SSY47SFCQFICC6WWHPJP6JR56SKWXTSR9B")
