import boa
from tests.utils.deployers import (
    CONSTANTS_DEPLOYER,
    CONTROLLER_DEPLOYER,
    LENDING_FACTORY_DEPLOYER,
)

ZERO_ADDRESS = boa.eval("empty(address)")
MAX_UINT256 = boa.eval("max_value(uint256)")

# Constants from contracts/constants.vy
WAD = CONSTANTS_DEPLOYER._constants.WAD
SWAD = CONSTANTS_DEPLOYER._constants.SWAD
DEAD_SHARES = CONSTANTS_DEPLOYER._constants.DEAD_SHARES

MAX_ORACLE_PRICE_DEVIATION = CONTROLLER_DEPLOYER._constants.MAX_ORACLE_PRICE_DEVIATION
MIN_TICKS = CONTROLLER_DEPLOYER._constants.MIN_TICKS
MAX_TICKS = CONTROLLER_DEPLOYER._constants.MAX_TICKS

MIN_A = LENDING_FACTORY_DEPLOYER._constants.MIN_A
MAX_A = LENDING_FACTORY_DEPLOYER._constants.MAX_A
MIN_FEE = LENDING_FACTORY_DEPLOYER._constants.MIN_FEE
MAX_FEE = LENDING_FACTORY_DEPLOYER._constants.MAX_FEE
MAX_LOAN_DISCOUNT = LENDING_FACTORY_DEPLOYER._constants.MAX_LOAN_DISCOUNT
MIN_LIQUIDATION_DISCOUNT = LENDING_FACTORY_DEPLOYER._constants.MIN_LIQUIDATION_DISCOUNT
